### ISSUE TITLE
Found error in ApiHandler

### ISSUE THREAD

**Issue by lrconsult** [LordHepipud/icingaweb2-module-windows#20]
The error I had with the icinga-module-windows
https://github.com/LordHepipud/icinga-module-windows/issues/12

was caused by an error in this update statement:
/usr/share/icingaweb2/modules/windows/library/Windows/CheckResultApi/ApiHandler.php, line 97:
**Filter::expression('host_id', '=', $this->json['fqdn'])**

should be:
**Filter::expression('host', '=', $this->json['fqdn'])**

**Comment by LordHepipud** [comment]
Thank you for the input - indeed it looks like I used the wring filter here.
I will take a look on that and fix it shortly.

Thank you very much!

**Comment by lrconsult** [comment]
Wenn du Lust & Zeit hast, können wir uns mal austauschen :-)

**Comment by LordHepipud** [comment]
Können wir sehr gerne machen - Issue ist fixed :)
Danke nochmal !

**Comment by lrconsult** [comment]
schreib mir gerne: Ralf.Lueders@lrconsult.com
Skype: ralf.lueders
