### ISSUE TITLE
Hosts are not displayed under the Hosts view. What conditions must be met on the host?

### ISSUE THREAD

**Issue by plsatin** [LordHepipud/icingaweb2-module-windows#22]
Hosts are not displayed under the Hosts view. What conditions must be met on the host?

![image](https://user-images.githubusercontent.com/20735310/69775101-8b2fa980-11b9-11ea-95d1-42816c2cb29f.png)

**Comment by LordHepipud** [comment]
The Web-Module is not yet supported due to plenty of re-writes of the Powershell core module.
Once the framework itself is polished properly, I will continue on the web part.

**Comment by plsatin** [comment]
Thanks for the answer.
Can you briefly describe how the database is supposed to be populated? Through an Icinga2 agent?

**Comment by plsatin** [comment]
I am working on a hardware inventory project on Windows hosts. At the moment, in my module, data is written directly to an external database.
My module: https://github.com/plsatin/icingaweb2-module-hardwareinfo

**Comment by LordHepipud** [comment]
The database is filled by using the Icinga Web 2 Module. It provides an interface to accept Rest-API Calls which allowed the old module to connect there and post metadata about services, processes and general information like CPU and memory.

The problem with this mechanism is, that each Windows systems required direct access to the web module, which was not granted within every environment

**Comment by plsatin** [comment]
Thanks for the answer.
